# Generated by Django 4.2.12 on 2024-05-07 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
            },
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Форма',
                'verbose_name_plural': 'Формы',
            },
        ),
        migrations.AlterModelOptions(
            name='carpet',
            options={'verbose_name': 'Ковёр', 'verbose_name_plural': 'Ковры'},
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Элемент корзины', 'verbose_name_plural': 'Элементы корзины'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Элемент заказа', 'verbose_name_plural': 'Элементы заказа'},
        ),
        migrations.RemoveField(
            model_name='carpet',
            name='category',
        ),
        migrations.RemoveField(
            model_name='carpet',
            name='color',
        ),
        migrations.RemoveField(
            model_name='carpet',
            name='country_of_origin',
        ),
        migrations.RemoveField(
            model_name='carpet',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='carpet',
            name='image',
        ),
        migrations.RemoveField(
            model_name='carpet',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='carpet',
            name='style',
        ),
        migrations.RemoveField(
            model_name='carpet',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='carpet',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='carpet',
            name='pile_height',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='carpet',
            name='colors',
            field=models.ManyToManyField(to='store.color'),
        ),
        migrations.AddField(
            model_name='carpet',
            name='country',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.country'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carpet',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.material'),
        ),
        migrations.AlterField(
            model_name='carpet',
            name='shape',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.shape'),
        ),
    ]
