# Generated by Django 4.2.12 on 2024-05-07 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0002_color_country_material_shape_alter_carpet_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carpet',
            name='size',
        ),
        migrations.AddField(
            model_name='carpet',
            name='height',
            field=models.DecimalField(decimal_places=1, default=None, max_digits=10, verbose_name='Высота, см'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carpet',
            name='width',
            field=models.DecimalField(decimal_places=1, default=None, max_digits=10, verbose_name='Ширина, см'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carpet',
            name='colors',
            field=models.ManyToManyField(to='store.color', verbose_name='Цвета'),
        ),
        migrations.AlterField(
            model_name='carpet',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.country', verbose_name='Страна производства'),
        ),
        migrations.AlterField(
            model_name='carpet',
            name='description',
            field=models.TextField(max_length=2000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='carpet',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.material', verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='carpet',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='carpet',
            name='pile_height',
            field=models.IntegerField(max_length=6, verbose_name='Высота ворса, мм'),
        ),
        migrations.AlterField(
            model_name='carpet',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена, ₽'),
        ),
        migrations.AlterField(
            model_name='carpet',
            name='shape',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.shape', verbose_name='Форма'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(through='store.CartItem', to='store.carpet', verbose_name='Ковры'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='carpet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.carpet', verbose_name='Ковёр'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.cart', verbose_name='Корзина'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(max_length=6, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(max_length=2000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='order',
            name='carpets',
            field=models.ManyToManyField(through='store.OrderItem', to='store.carpet', verbose_name='Ковёр'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итого ₽'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='carpet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.carpet', verbose_name='Ковёр'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(max_length=6, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена ₽'),
        ),
        migrations.AlterField(
            model_name='shape',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
