# Generated by Django 4.2.12 on 2024-05-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_carpet_size_carpet_height_carpet_width_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='carpets/', verbose_name='Фото'),
        ),
    ]
