# Generated by Django 4.2.12 on 2024-05-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_carpet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='store/static/images/carpets', verbose_name='Фото'),
        ),
    ]
