# Generated by Django 4.2.12 on 2024-05-07 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_carpet_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpet',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.category', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
