# Generated by Django 4.2.12 on 2024-05-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_carpet_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='store/static/images/carpets', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
            },
        ),
        migrations.RemoveField(
            model_name='carpet',
            name='image',
        ),
        migrations.RemoveField(
            model_name='carpet',
            name='material',
        ),
        migrations.AddField(
            model_name='carpet',
            name='materials',
            field=models.ManyToManyField(to='store.material', verbose_name='Материалы'),
        ),
        migrations.AlterField(
            model_name='carpet',
            name='pile_height',
            field=models.IntegerField(verbose_name='Высота ворса, мм'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='carpet',
            name='images',
            field=models.ManyToManyField(to='store.image', verbose_name='Фото'),
        ),
    ]
