# Generated by Django 4.2.12 on 2024-05-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_image_remove_carpet_image_remove_carpet_material_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carpet',
            name='height',
        ),
        migrations.AddField(
            model_name='carpet',
            name='length',
            field=models.DecimalField(decimal_places=1, default=230, max_digits=10, verbose_name='Длина, см'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/carpets', verbose_name='Фото'),
        ),
    ]
