# Generated by Django 4.2.12 on 2024-05-09 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_carpet_height_carpet_length_alter_image_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Ширина, см')),
                ('length', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Длина, см')),
            ],
            options={
                'verbose_name': 'Размер',
                'verbose_name_plural': 'Размеры',
            },
        ),
        migrations.RemoveField(
            model_name='carpet',
            name='length',
        ),
        migrations.RemoveField(
            model_name='carpet',
            name='width',
        ),
        migrations.AddField(
            model_name='carpet',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.size', verbose_name='Размер'),
        ),
    ]
