# Generated by Django 4.2.12 on 2024-05-11 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_size_remove_carpet_length_remove_carpet_width_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='carpet',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='order',
            name='carpets',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='carpet',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
