# Generated by Django 5.0.6 on 2024-05-19 12:59

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='hex_value',
            field=colorfield.fields.ColorField(default='#FFFFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Выберите значение'),
        ),
    ]
