# Generated by Django 5.0.6 on 2024-05-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_color_hex_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='description',
            field=models.TextField(default='Нет', max_length=200, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(max_length=200, verbose_name='Описание'),
        ),
    ]
