# Generated by Django 5.0.6 on 2024-05-19 14:22

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_material_description_alter_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='hex_value',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Выберите значение'),
        ),
        migrations.AlterField(
            model_name='material',
            name='description',
            field=models.TextField(max_length=250, verbose_name='Описание'),
        ),
    ]
