# Generated by Django 5.0.6 on 2024-05-26 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_color_hex_value_alter_material_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carpet',
            name='size',
        ),
        migrations.CreateModel(
            name='CarpetSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Ширина, см')),
                ('length', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Длина, см')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество')),
                ('carpet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carpet_sizes', to='store.carpet', verbose_name='Ковёр')),
            ],
            options={
                'verbose_name': 'Размер ковра',
                'verbose_name_plural': 'Размеры ковров',
            },
        ),
        migrations.DeleteModel(
            name='Size',
        ),
        migrations.AddConstraint(
            model_name='carpetsize',
            constraint=models.UniqueConstraint(fields=('carpet', 'width', 'length'), name='unique_carpet_size'),
        ),
    ]
