# Generated by Django 5.0.6 on 2024-05-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_remove_carpet_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carpet',
            name='waiting_days',
        ),
        migrations.AddField(
            model_name='carpetsize',
            name='waiting_days',
            field=models.IntegerField(default=0, verbose_name='Время ожидания в днях'),
        ),
    ]
