# Generated by Django 5.0.6 on 2024-05-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_remove_carpet_waiting_days_carpetsize_waiting_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carpet',
            name='price',
        ),
        migrations.AddField(
            model_name='carpetsize',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена, ₽'),
        ),
    ]
