# Generated by Django 4.2.12 on 2024-05-11 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_carpet_quantity_carpet_waiting_days'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='subtotal',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
        migrations.RemoveField(
            model_name='order',
            name='carpets',
        ),
        migrations.AddField(
            model_name='cart',
            name='carpet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.carpet', verbose_name='Ковёр'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='created_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=None, verbose_name='Дата добавления'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=None, verbose_name='Количество'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='created_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=None, verbose_name='Дата продажи'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
