# Generated by Django 5.0.6 on 2024-05-11 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_cart_quantity_alter_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
