# Generated by Django 5.0.6 on 2024-05-26 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_phone_number'),
        ('store', '0019_remove_carpet_price_carpetsize_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='carpet',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='carpet',
        ),
        migrations.AddField(
            model_name='cart',
            name='carpet_size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.carpetsize', verbose_name='Ковёр'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='carpet_size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.carpetsize', verbose_name='Ковёр'),
        ),
    ]
